# This override file will be automatically used with docker-compose up
services:
  trip-management:
    env_file:
      - .env
    volumes:
      - ./trip-management:/app
    networks:
      - voyage
  mongo-trip:
    env_file:
      - .env
    networks:
      - voyage

  recommendations:
    env_file:
      - .env
    volumes:
      - ./recommendations/app:/app
    networks:
      - voyage

  recommendations_cache:
    env_file:
      - .env
    networks:
      - voyage

  place-wrapper:
    env_file:
      - .env
    volumes:
      - ./place-wrapper:/app:Z
    networks:
      - voyage

  place_wrapper_cache:
    env_file:
      - .env
    networks:
      - voyage

  maps-wrapper:
    env_file:
      - .env
    networks:
      - voyage
    volumes:
      - ./maps-wrapper/app:/app:Z

  maps_wrapper_cache:
    env_file:
      - .env
    networks:
      - voyage

  frontend:
    env_file:
      - .env
    volumes:
      - ./frontend:/ui
      - /ui/node_modules
    networks:
      - voyage

