services:
  trip-management:
    ports:
      - "8081:8080"
    networks:
      - voyage
  recommendations:
    ports:
      - "8082:8080"
    networks:
      - voyage
  place-wrapper:
    ports:
      - "8083:8080"
    networks:
      - voyage
