# This override file will be automatically used with docker-compose up
services:
  trip-management:
    networks:
      - voyage
  mongo-trip:
    networks:
      - voyage

  recommendations:
    networks:
      - voyage

  recommendations_cache:
    networks:
      - voyage

  place-wrapper:
    networks:
      - voyage

  place_wrapper_cache:
    networks:
      - voyage

  maps-wrapper:
    networks:
      - voyage

  maps_wrapper_cache:
    networks:
      - voyage

  frontend:
    networks:
      - voyage

