include:
  - trip-management/docker-compose.yaml
  - recommendations/docker-compose.yaml
  - place-wrapper/docker-compose.yaml
  - maps-wrapper/docker-compose.yaml

services:
  reverse-proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: reverse-proxy
    ports:
      - "443:443"
      - "80:80"
    networks:
      - voyage
    depends_on:
      - trip-management
      - recommendations
      - place-wrapper
      - maps-wrapper

networks:
  voyage:
    driver: bridge
