# This override file will be automatically used with docker-compose up
services:
  trip-management:
    env_file:
      - .env
    networks:
      - voyage
  mongo-trip:
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASSWORD}
    networks:
      - voyage
    volumes:
      - orchestrator_mongo-data:/data/db
  trip-cache:
    env_file:
      - .env
    networks:
      - voyage

  recommendations:
    env_file:
      - .env
    networks:
      - voyage

  recommendations_cache:
    env_file:
      - .env
    networks:
      - voyage

  place-wrapper:
    env_file:
      - .env
    networks:
      - voyage

  place_wrapper_cache:
    env_file:
      - .env
    networks:
      - voyage

  maps-wrapper:
    env_file:
      - .env
    networks:
      - voyage

  maps_wrapper_cache:
    env_file:
      - .env
    networks:
      - voyage
  user-management:
    env_file:
      - .env
    networks:
      - voyage

  landing-page:
    env_file:
      - .env
    networks:
      - voyage

volumes:
  orchestrator_mongo-data:
    external: true
