# This override file will be automatically used with docker-compose up
services:
  trip-management:
    env_file:
      - .env
    volumes:
      - ./trip-management:/app:Z
    networks:
      - voyage
  mongo-trip:
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPASSWORD}
    volumes:
      - orchestrator_mongo-data:/data/db
    restart: always
    # Add container name to ensure consistent naming
    container_name: mongo-trip
    networks:
      - voyage
  trip-cache:
    env_file:
      - .env
    networks:
      - voyage
  recommendations:
    env_file:
      - .env
    volumes:
      - ./recommendations/app:/app:Z
    networks:
      - voyage

  recommendations_cache:
    env_file:
      - .env
    networks:
      - voyage

  place-wrapper:
    env_file:
      - .env
    volumes:
      - ./place-wrapper:/app:Z
    networks:
      - voyage

  place_wrapper_cache:
    env_file:
      - .env
    networks:
      - voyage

  maps-wrapper:
    env_file:
      - .env
    networks:
      - voyage
    volumes:
      - ./maps-wrapper/app:/app:Z

  maps_wrapper_cache:
    env_file:
      - .env
    networks:
      - voyage

  frontend:
    env_file:
      - .env
    volumes:
      - ./frontend:/ui
      - /ui/node_modules
    networks:
      - voyage
  user-management:
    env_file:
      - .env
    volumes:
      - ./user-management/app:/app:Z
    networks:
      - voyage

  landing-page:
    env_file:
      - .env
    volumes:
      - ./landing-page:/app:Z
      - /app/node_modules
    networks:
      - voyage

# Define the volume with explicit configuration
volumes:
  orchestrator_mongo-data:
    external: true
