name: Deploy to Azure VM on PR merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - closed # Trigger when the pull request is closed (i.e., merged)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

      - name: Connect to Azure VM and deploy
        run: |
          ssh -o StrictHostKeyChecking=no voyage@20.199.95.151 << 'EOF'
            cd orchestrator
            docker compose down
            git restore .
            git checkout main
            git pull origin main
            mkdir certs
            cp ../certs/voyage_certificate.crt ./certs/voyage_certificate.crt
            cp ../certs/voyage_private.key ./certs/voyage_private.key
            cp ../certs/landing_certificate.crt ./certs/landing_certificate.crt
            cp ../certs/landing_private.key ./certs/landing_private.key
            git submodule update --recursive
            git submodule foreach git checkout dev
            git submodule foreach git pull
            chmod +x deploy.sh
            ./deploy.sh
          EOF
