name: Deploy to Azure VM on PR merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - closed  # Trigger when the pull request is closed (i.e., merged)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

      - name: Connect to Azure VM and deploy
        run: |
          ssh -o StrictHostKeyChecking=no voyage@20.199.95.151 << 'EOF'
            cd orchestrator
            docker-compose down
            restore .
            git checkout main
            git pull origin main
            chmod +x deploy.sh
            ./deploy.sh
          EOF

